# Generated by Django 2.0.6 on 2018-06-11 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='', max_length=50)),
                ('platform_description', models.TextField(blank=True, default='', max_length=280, null=True)),
                ('public_display', models.BooleanField(default=False)),
                ('website', models.URLField(help_text='Your Landing page URL.', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=280, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.ManyToManyField(to='core.Type_of_Platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
