# Generated by Django 2.0.6 on 2018-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='source_description',
            field=models.TextField(blank=True, default='', max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='source_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
