# Generated by Django 2.0.6 on 2018-06-12 10:04

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180611_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=core.models.platform_image_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='platform',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sources',
            name='platform_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_sources', to='core.platform'),
        ),
    ]
