# Generated by Django 2.0.6 on 2018-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180612_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='side_note',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
