# Generated by Django 2.0.6 on 2018-06-12 10:25

import advertisment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=advertisment.models.advertisment_image_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('client_name', models.CharField(default='', max_length=50)),
                ('client_description', models.TextField(blank=True, default='', max_length=280, null=True)),
                ('public_display', models.BooleanField(default=False)),
                ('website', models.URLField(help_text='Your Landing page URL.', max_length=1000)),
                ('click_count', models.IntegerField(default=0)),
                ('advert_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
