# Generated by Django 2.0.6 on 2018-06-14 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='advert_lifespan',
            field=models.IntegerField(choices=[(1, '1 Day'), (7, '7 Days'), (28, '28 Days')], default=1, help_text='Number of days you want the advert to be live'),
        ),
        migrations.AddField(
            model_name='ads',
            name='advert_status',
            field=models.CharField(choices=[('Unpaid', 'unpaid'), ('Paid', 'paid'), ('Displaying', 'displaying'), ('Completed', 'completed')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='ads',
            name='advert_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ads',
            name='advert_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
