# Generated by Django 2.0.6 on 2018-07-18 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=20)),
                ('started', models.DateField()),
                ('work_description', models.TextField(max_length=280)),
                ('source_name', models.CharField(default='', max_length=50)),
                ('source_description', models.TextField(blank=True, default='', max_length=280, null=True)),
                ('public_display', models.BooleanField(default=False)),
                ('website', models.URLField(help_text='Your Landing page URL.', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
