# Generated by Django 2.0.6 on 2018-07-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_contact_details_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_details',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Contact Detail', 'verbose_name_plural': 'Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Queue', 'verbose_name_plural': 'Queues'},
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='contact',
            field=models.CharField(help_text='Guest contact name.', max_length=100),
        ),
    ]
