# Generated by Django 2.0.6 on 2018-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180721_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='guest_contact',
        ),
        migrations.AddField(
            model_name='queue',
            name='guest_contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='guest_queue', to='people.contact_details'),
        ),
    ]
