# Generated by Django 2.0.6 on 2018-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20180905_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
